# Production Docker Compose for Esoteric Vectors
# Pulls image from Docker Hub: daniel1mathias/esoteric-vectors:latest
# Domain: mystical-mentor.beautiful-apps.com (HTTPS)

services:
  # Mystic Mentor Backend (Crowdfunding Due Diligence)
  backend:
    build: .
    container_name: mystic-mentor-backend
    restart: unless-stopped
    
    # Load ALL environment variables from .env file
    env_file: .env
    
    # nginx-proxy configuration for automatic SSL and routing
    environment:
      VIRTUAL_HOST: mystical-mentor.beautiful-apps.com
      VIRTUAL_PORT: 8002
      LETSENCRYPT_HOST: mystical-mentor.beautiful-apps.com
      LETSENCRYPT_EMAIL: nex.mod.daniel@gmail.com
    
    volumes:
      # Persistent data storage
      - ./data:/app/data
      - ./logs:/app/logs
    
    networks:
      - proxy
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  conf:
  html:
  certs:
  acme:

networks:
  proxy:
    external: true

# Resource limits and monitoring
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3" 