# Production Docker Compose for Esoteric Vectors
# Pulls image from Docker Hub: daniel1mathias/esoteric-vectors:latest
# Domain: mystical-mentor.beautiful-apps.com (HTTPS)

version: '3.8'

services:
  # Automatic nginx proxy for SSL and routing
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "local"
    volumes:
      - conf:/etc/nginx/conf.d
      - /root/nginx/vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  # Automatic SSL certificate management with Let's Encrypt
  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      DEFAULT_EMAIL: nex.mod.daniel@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  # Crowdfunding Due Diligence Backend
  backend:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      # nginx-proxy configuration for automatic SSL and routing
      - VIRTUAL_HOST=mystical-mentor.beautiful-apps.com
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=mystical-mentor.beautiful-apps.com
      - LETSENCRYPT_EMAIL=nex.mod.daniel@gmail.com
    volumes:
      - ./data:/app/data
      - ./web:/app/web:ro
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  conf:
  html:
  certs:
  acme:

networks:
  proxy:
    external: true

# Resource limits and monitoring
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3" 